import Vector2 from '../src/Structs/Vector2'

export const TankPacketNames = [
  "PACKET_STATE", "PACKET_CALL_FUNCTION", "PACKET_UPDATE_STATUS", "PACKET_TILE_CHANGE_REQUEST", "PACKET_SEND_MAP_DATA",
  "PACKET_SEND_TILE_UPDATE_DATA", "PACKET_SEND_TILE_UPDATE_DATA_MULTIPLE", "PACKET_TILE_ACTIVATE_REQUEST", "PACKET_TILE_APPLY_DAMAGE",
  "PACKET_SEND_INVENTORY_STATE", "PACKET_ITEM_ACTIVATE_REQUEST", "PACKET_ITEM_ACTIVATE_OBJECT_REQUEST", "PACKET_SEND_TILE_TREE_STATE",
  "PACKET_MODIFY_ITEM_INVENTORY", "PACKET_ITEM_CHANGE_OBJECT", "PACKET_SEND_LOCK", "PACKET_SEND_ITEM_DATABASE_DATA", "PACKET_SEND_PARTICLE_EFFECT",
  "PACKET_SET_ICON_STATE", "PACKET_ITEM_EFFECT", "PACKET_SET_CHARACTER_STATE", "PACKET_PING_REPLY", "PACKET_PING_REQUEST", "PACKET_GOT_PUNCHED",
  "PACKET_APP_CHECK_RESPONSE", "PACKET_APP_INTEGRITY_FAIL", "PACKET_DISCONNECT", "PACKET_BATTLE_JOIN", "PACKET_BATTLE_EVENT", "PACKET_USE_DOOR",
  "PACKET_SEND_PARENTAL", "PACKET_GONE_FISHIN", "PACKET_STEAM", "PACKET_PET_BATTLE", "PACKET_NPC", "PACKET_SPECIAL", "PACKET_SEND_PARTICLE_EFFECT_V2",
  "PACKET_ACTIVE_ARROW_TO_ITEM", "PACKET_SELECT_TILE_INDEX", "PACKET_SEND_PLAYER_TRIBUTE_DATA", "PACKET_SET_EXTRA_MODS", "PACKET_ON_STEP_ON_TILE_MOD",
  "PACKET_ERRORTYPE"
]

export enum MessageTypes {
  HLO = 1,
  STR,
  ACT,
  TNK
}

export enum TankOffsets {
  PACKET_TYPE           = 4,
  PACKET_NET_ID_CURRENT = 8,
  PACKET_NET_ID_TARGET  = 12,
  PACKET_STATE          = 16,
  PACKET_INFO           = 24, /* TODO: Find a better name */
  PACKET_PLAYER_X_POS   = 28,
  PACKET_PLAYER_Y_POS   = 32,
  PACKET_PLAYER_X_SPEED = 36,
  PACKET_PLAYER_Y_SPEED = 40,
  PACKET_PLAYER_X_PUNCH = 48,
  PACKET_PLAYER_Y_PUNCH = 52,
  PACKET_EXTRA_DATA_LEN = 56,
  PACKET_EXTRA_DATA     = 60
}

export interface NetUser {
  current?: number
  target?: number
}

export interface TankData {
  type?: number
  net?: NetUser
  state?: number
  p0?: number
  info?: number
  pos?: Vector2
  speed?: Vector2
  p1?: number
  punch?: Vector2
  extra?: () => Buffer
}